name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.3
  equatable: ^1.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  http: ^0.12.2
  http_parser: ^3.1.4
  # video_player: ^2.4.2
  video_player: 
    git:
        url: https://gitlab.com/dovandu/plugins.git
        path: packages/video_player/video_player

dev_dependencies:

flutter:
